@startuml 项目申报流程

title 三下乡项目申报流程

|学生|
start
:创建项目;
:填写信息;
:提交审批;

|学院管理员|
if (审批?) then (驳回)
  :填写驳回原因;
  |学生|
  :修改项目;
  :重新提交;
  detach
else (通过)
endif

|校级管理员|
if (审批?) then (驳回)
  :填写驳回原因;
  |学生|
  :修改项目;
  :重新提交;
  detach
else (通过)
endif

:项目立项;

|指导教师|
:项目结项;
:进入评优;

stop

@enduml
